### ISSUE TITLE
Move this hook definition to pre-commit-hooks

### ISSUE THREAD

**Issue by ssbarnea** [ryanrhee/shellcheck-py#6]
Shellcheck is already a very popular tool and in order to avoid adding a new git clonning to pre-commit hooks it would make sense to include the hook definiton in the main https://github.com/pre-commit/pre-commit-hooks repository.

**Comment by asottile** [comment]
no thanks

**Comment by ssbarnea** [comment]
@asottile I seen you also closed https://github.com/pre-commit/pre-commit-hooks/pull/441 without any explanation.

I was not able to find anything in the repository README indicating that contributors are not welcomed. Maybe it would make sense to document these.

From what I understand it would be considerd fine to endup with a pre-commit config file that inside links to 50 other git repos which are all cloned one by one, from whatever random git repository the original author created them.

**Comment by asottile** [comment]
Honestly at this point I don't think I owe you another explanation, I've explained this exact thing to you many times and I'm becoming tired of doing so:

- https://github.com/pre-commit/pre-commit-hooks/pull/440#pullrequestreview-348926105 (just 7 days ago!!!)
- https://github.com/pre-commit/pre-commit-hooks/issues/344#issuecomment-518005728
- https://github.com/pre-commit/pre-commit-hooks/issues/406
- https://github.com/pre-commit/pre-commit/issues/942
- https://github.com/pre-commit/pre-commit-hooks/issues/81#issuecomment-404876421

(and probably more but I don't have time to track them all down).  nobody else has complained about this "problem" so I'm convinced it's a you-problem -- please stop bring it it up I am not going to change this.
